services:
  - type: web
    name: system-raportowania
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y wkhtmltopdf
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
